name: setup-git
description: 'Setup git'
runs:
  using: 'composite'
  steps:
    - name: Git check
      run: |
        git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "$(gh api /users/${GITHUB_ACTOR} | jq .name -r)"
        git config -l
      shell: bash
