name: Build Python Package

on: [workflow_call, workflow_dispatch]

jobs:
  build-package:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Package
        uses: hynek/build-and-inspect-python-package@v2
        with:
          attest-build-provenance-github: 'true'
