name: Display the version hint
on:
  pull_request:
    types: [synchronize]
    branches: [master]

jobs:
  bumpversion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies

      - name: Install requirements
        run: |
          python -m pip install . bump-my-version

      - name: Git check
        run: |
          git config --global user.email "no-reply@github.actions"
          git config --global user.name "Testing Git"
          git --version
          git config --list

      - name: Get the release hint
        id: generate-changelog
        run: |
          RELEASE_KIND=$(generate-changelog --output release-hint --branch-override ${{ github.base_ref }} --skip-output-pipeline)
          echo "::notice::Suggested release type upon merge to ${{ github.base_ref }}: ${RELEASE_KIND}"
          echo "RELEASE_KIND=$RELEASE_KIND" >> $GITHUB_ENV
          echo "release-kind=$RELEASE_KIND" >> $GITHUB_OUTPUT

      - name: Bump Version dry run
        if: ${{ env.RELEASE_KIND != 'no-release' }}
        shell: bash
        run: |
          PR_NUMBER=$(gh pr view --json number -q .number || echo "")
          REVISION=$(git describe --tags --long | awk -F- '{print $2}')
          export PR_NUMBER REVISION

          # This will display a full log of what would happen if we were to bump the version.
          bump-my-version bump --dry-run --verbose "$RELEASE_KIND"

          # This retrieves the current and new version numbers as a JSON-formatted string.
          VERSION_INFO=$(bump-my-version show --format json --increment "$RELEASE_KIND" current_version new_version)
          echo "CURRENT_VERSION=$(echo $VERSION_INFO | jq -r .current_version)" >> $GITHUB_ENV
          echo "NEW_VERSION=$(echo $VERSION_INFO | jq -r .new_version)" >> $GITHUB_ENV

      - name: Set no-release information
        if: ${{ env.RELEASE_KIND == 'no-release' }}
        run: |
          echo "CURRENT_VERSION=$(bump-my-version show current_version)" >> $GITHUB_ENV
          echo "NEW_VERSION=$(bump-my-version show current_version)" >> $GITHUB_ENV

      - name: Display the version hint
        uses: s-gehring/singleton-comment@v1
        with:
          comment-body: |
            **Version hint:** ${{ env.RELEASE_KIND }}
            **Current version:** ${{ env.CURRENT_VERSION }}
            **New version (when merged):** ${{ env.NEW_VERSION }}
