name: Publish Documentation

on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}


jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup Python
        uses: ./.github/actions/checkout-and-setup-python
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[docs]"
      - name: Build and publish docs
        run: make pubdocs
