name: Publish Preview Documentation

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  publish-docs:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      pages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Set up Git
      uses: ./.github/actions/setup-git

    - name: Install dependencies
      run: uv sync --group docs

    - name: Build and publish docs
      run: uv run mkdocs gh-deploy --strict
