name: Release to GitHub
on:
  workflow_call:
    inputs:
      ref:
        description: The branch, tag or SHA to checkout. Otherwise, uses the default branch.
        required: true
        type: string

jobs:
  release-github:
    name: Create a GitHub release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout the repository
        with:
          fetch-depth: 0

      - name: Setup Git
        uses: fregante/setup-git-user@v2

      - name: release-notes
        uses: callowayproject/action-changelog-to-releasenotes@main
        with:
          target-version: ${{ inputs.ref }}

      - name: Download packages built by build-and-inspect-python-package
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          tag_name: ${{ inputs.ref }}
          body_path: release-notes.md
