name: Release to Python
on:
  workflow_call: {} # This workflow requires the artifacts from build-python.yaml

jobs:
  release-pypi:
    name: Publish released package to pypi.org
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Download packages built by build-and-inspect-python-package
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
